#!/usr/bin/bash

# Auteur : Étienne St-Amant-Audet
# Cours  : 420 155 MO
# Date   : 15 mai 2015
#
# Fichier : archiver
#
# Ce script permet d'archiver un repertoire quelconque et
# et de déposer l'archive dans le repertoire d'archive 
# $HOME/archives. 2 paramètres doivent être envoyés au script.
# Le premier représente le nom du repertoire à archiver et le 
# deuxième, le nom de l'archive.

# Début du script 

ok="vrai"
if (( $# < 2 )) ; then
   echo -e "\nErreur, il y a moins de 2 paramètres envoyés au script." >&2
   ok="faux"
elif (( $# > 2 )) ; then
   echo -e "\nErreur, il y a plus de 2 paramètres envoyés au script." >&2
   ok="faux"
fi
if [[ "$ok" == "faux" ]] ; then
   echo -e "\nCe script doit recevoir exactement deux paramètres." >&2
   echo -e "\nVous devez donner 2 arguments après l'appel du script ex: (./archiver nomRep nomArchive)" >&2
   exit 1
fi
if [[ !(-e $HOME/archives) && !(-d $HOME/archives) ]] ; then
   echo -e "\nCréation du répertoire $HOME/archives.\n" >&2
   mkdir $HOME/archives &> /dev/null
   if (( $? != 0 )) ; then
      echo "\nLa création du répertoire $HOME/archives a échouée.\n" >&2
      exit 1
   fi
elif [[ -e $HOME/archives && !(-d $HOME/archives) ]] ; then
   echo -e "\nErreur, un fichier $HOME/archives existe déjà.\n" >&2
   exit 1
elif [[ !(-w $HOME/archives) ]] ; then
   echo -e "\nErreur, le repertoire $HOME/archives n'est pas permis en écriture.\n"
   exit 1
fi
if [[ !(-e $1) ]] ; then
   echo -e "\nErreur, le repertoire $1 n'existe pas.\n" >&2
   exit 1
elif [[ -e $1 && !(-d $1) ]] ; then
   echo -e "\nErreur, le fichier $1 n'est pas un répertoire.\n" >&2
   exit 1
elif [[ -e $1 && !(-r $1) ]] ; then
   echo -e "\nErreur, le repertoire $1 n'est pas permis en lecture.\n" >&2
   exit 1
fi
ficTemp=$(/usr/bin/mktemp)
echo -e "\nCréation de l'archive..."
tar -cf $ficTemp $1 &> /dev/null
if (( $? != 0 )) ; then
   echo -e "\nErreur, la création de l'archive a échouée." >&2 
   rm -r $ficTemp
   exit 1
fi
echo -e "\nCompression de l'archive..."
xz -9 $ficTemp &> /dev/null
if (( $? != 0 )) ; then
   echo -e "\nErreur, la compression de l'archive a échouée.\n" >&2
   rm -r $ficTemp
   exit 1
fi
echo -e "\nDéplacement de l'archive dans $HOME/archives....\n"
mv $ficTemp.xz $HOME/archives/$2-$(date +%Y%m%d-%Hh%mm%Ss).txz
if (( $? != 0 )) ; then
   echo -e "\nErreur, le déplacement de l'archive a échouée.\n" >&2
   rm -r $ficTemp
   exit 1
fi
