#!/bin/bash

# Auteur : Étienne St-Amant-Audet
# Cours  : 420 217 MO
# Date   : 02/2015
#
# Fichier : bckfic
#
# Ce script permet de faire une copie de sauvegarde d'un seul fichier et 
# d'ajouter la date en extension. 
# Il reçoit seulement un paramètre : le fichier à copier.

# Début du script

ok="vrai"
   
# Validation du nombre de paramètres

if (( $# < 1 )) ; then
   echo -e "\nErreur, il n'y a pas de paramètre envoyé au script.\n" >&2
   ok="faux"
elif (( $# > 1 )) ; then
   echo -e "\nErreur, il y a plus d'un paramètre envoyé au script.\n" >&2
   ok="faux"
fi

if [[ ok == "faux" ]] ; then
   echo -e "\nVous devez mettre le paramètre en argument juste après"
   echo -e "l'appel du script. Ex : $0 PARAM\n"
   exit 1
fi
 
   
# Validation du fichier reçu en paramètre

if [[ ! -e $1 ]] ; then
   echo -e  "Erreur, le fichier $1 n'existe pas.\n" >&2
   exit 1
elif [[ ! -f $1 ]] ; then
   echo -e "\nErreur, le fichier $1 n'est pas un fichier ordinaire.\n" >&2
   exit 1
elif [[ ! -r $1 ]] ; then
   echo -e "\nErreur, le fichier $1 n'est pas permis en lecture.\n" >&2
fi

# On créé le fichier de backup

cp -i $1{,.$(date +%Y-%m-%d-%Hh%M)}
if (( $? != 0 )) ; then
   echo -e "\nErreur, la copie a échouée.\n" >&2
   exit 1
fi
